shallow_clone: true
branches:
  only:
    - master

platform:
  # - x86
  - x64

configuration:
  # - Debug
  - Release

image:
  - Visual Studio 2015
  # - Visual Studio 2017

environment:
  global:
      PYTHON: "C:\\conda"

  matrix:
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

skip_commits:
# Add [av skip] to commit messages
  message: /\[av skip\]/

# # To allow remote connection to appveyor
# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  ############################################################################
  # Install Conda
  ############################################################################
  - "git clone --depth 1 git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  ############################################################################
  # Install Conda
  ############################################################################
  - conda config --add channels conda-forge
  - conda install cmake swig

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmmd: set INSTALL_DIR=%APPVEYOR_BUILD_FOLDER%\build\simulate_install_dir
  - ps: |
      mkdir build
      cd build

  - ps: $env:CMAKE_PREFIX_PATH='C:\conda\Library\'
  - cmake -G "Visual Studio 14 2015 Win64"   ^
      -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR%   ^
      -DCMAKE_PREFIX_PATH=%MY_CONDA_PATH%    ^
      %APPVEYOR_BUILD_FOLDER%

build_script:
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --target install --config %CONFIGURATION%

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - dir *.py /b/s
  - dir *.exe /b/s
  - cd %APPVEYOR_BUILD_FOLDER%\build\
  - ctest -V . -C %CONFIGURATION%

deploy: off

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
