language:
  - cpp

cache:
  ccache: true
  directories:
    - $HOME/downloads

env:
  global:
    - CONFIGURATION=Release
    - PYTHON_VERSION=3.6

matrix:
  include:
    - os: linux
    - os: osx

branches:
  only:
  - master

before_install:

  # Travis machines have 2 cores
  - JOBS=2

  # Handle everything using conda
  - git clone https://github.com/astropy/ci-helpers.git;
  - source ci-helpers/travis/setup_conda.sh;
  - source deactivate
  - conda install cmake swig


script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build_travis && cd build_travis
  - cmake .. -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/simulate_install_dir/
  - cmake --build .
  - cmake --build . --target install
  # - ctest -v .
  - env CTEST_OUTPUT_ON_FAILURE=1 make test

after_success:

notifications:
  email: false
